version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile.backend
    ports:
      - '8000:8000'
  frontend:
    env_file:
      - ./packages/frontend/.env
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile.frontend
    ports:
      - '80:80'