version: '3'
services:
  backend:
    image: mdctleo/chatbot-server-backend:latest
    env_file:
      - ./packages/backend/.env
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile.backend
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8002:8002'
  frontend:
    image: mdctleo/chatbot-server-frontend:latest
    env_file:
      - ./packages/frontend/.env
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile.frontend
    ports:
      - '8088:90'